version: "3"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: http-imgress
      EGRESS_API_HOST: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
    ports:
      - 5000:80
